const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Ensure results directory exists
const resultsDir = path.join(__dirname, '../../results');
if (!fs.existsSync(resultsDir)) {
  fs.mkdirSync(resultsDir, { recursive: true });
}

/**
 * Generate PDF report for video analysis
 * @param {Object} data - Analysis data
 * @returns {Promise<string>} - Path to generated PDF
 */
const generatePDFReport = (data) => {
  return new Promise((resolve, reject) => {
    try {
      const filename = `report-${data.video_id}-${Date.now()}.pdf`;
      const filepath = path.join(resultsDir, filename);
      
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filepath);
      
      doc.pipe(stream);

      // Header
      doc.fontSize(24)
         .fillColor('#2563eb')
         .text('DeepGuardAI', { align: 'center' })
         .moveDown(0.5);
      
      doc.fontSize(18)
         .fillColor('#000000')
         .text('Deepfake Detection Report', { align: 'center' })
         .moveDown(2);

      // Video Information
      doc.fontSize(14)
         .fillColor('#1e40af')
         .text('Video Information', { underline: true })
         .moveDown(0.5);
      
      doc.fontSize(11)
         .fillColor('#000000')
         .text(`Video ID: ${data.video_id}`)
         .text(`Filename: ${data.filename || 'N/A'}`)
         .text(`Analysis Date: ${new Date().toLocaleString()}`)
         .moveDown(1.5);

      // Detection Result
      doc.fontSize(14)
         .fillColor('#1e40af')
         .text('Detection Result', { underline: true })
         .moveDown(0.5);
      
      const statusColor = data.status === 'Real' ? '#16a34a' : '#dc2626';
      doc.fontSize(16)
         .fillColor(statusColor)
         .text(`Status: ${data.status}`, { bold: true })
         .moveDown(0.5);
      
      doc.fontSize(11)
         .fillColor('#000000')
         .text(`Confidence Score: ${(data.confidence * 100).toFixed(2)}%`)
         .moveDown(1.5);

      // Anomalies Detected
      if (data.anomalies && data.anomalies.length > 0) {
        doc.fontSize(14)
           .fillColor('#1e40af')
           .text('Anomalies Detected', { underline: true })
           .moveDown(0.5);
        
        data.anomalies.forEach((anomaly, index) => {
          doc.fontSize(11)
             .fillColor('#000000')
             .text(`${index + 1}. ${anomaly}`);
        });
        doc.moveDown(1.5);
      }

      // Analysis Details
      if (data.frames_analyzed) {
        doc.fontSize(14)
           .fillColor('#1e40af')
           .text('Analysis Details', { underline: true })
           .moveDown(0.5);
        
        doc.fontSize(11)
           .fillColor('#000000')
           .text(`Frames Analyzed: ${data.frames_analyzed}`)
           .text(`Processing Time: ${data.processing_time || 'N/A'}`)
           .moveDown(1.5);
      }

      // Recommendations
      doc.fontSize(14)
         .fillColor('#1e40af')
         .text('Recommendations', { underline: true })
         .moveDown(0.5);
      
      doc.fontSize(11)
         .fillColor('#000000');
      
      if (data.status === 'Fake') {
        doc.text('⚠ This video shows signs of manipulation.')
           .text('• Do not share or distribute this content')
           .text('• Verify the source before trusting the content')
           .text('• Report suspicious content to relevant authorities');
      } else {
        doc.text('✓ This video appears to be authentic.')
           .text('• No significant manipulation detected')
           .text('• However, always verify content from multiple sources')
           .text('• Stay vigilant about deepfake technology');
      }

      // Footer
      doc.moveDown(3)
         .fontSize(9)
         .fillColor('#6b7280')
         .text('This report was generated by DeepGuardAI - Deepfake Detection Platform', {
           align: 'center'
         })
         .text('For more information, visit our platform', {
           align: 'center'
         });

      doc.end();

      stream.on('finish', () => {
        resolve(filepath);
      });

      stream.on('error', (error) => {
        reject(error);
      });

    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generatePDFReport
};
